# use the shared Yast defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop_yast_style.yml

# Just raise the default threshold a little bit
Metrics/MethodLength:
  Max: 20

# Just raise the default threshold a little bit
Metrics/AbcSize:
  Max: 20

# journalctl output is UTF-8, so are the comments explaning it
Style/AsciiComments:
  Enabled: false
