language: ruby
before_install:
# disable rvm, use system Ruby
- rvm reset
- wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
- sh ./travis_setup.sh -p "yast2-devtools yast2" -g bundler
script:
- rake check:pot
- rubocop
- yardoc
- COVERAGE=1 bundle exec rake test:unit
- sudo rake install

